baseURL: "https://blog.gardenplanter.app/"
languageCode: "en-us"
title: "Planter"
theme: "PaperMod"

params:
    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "favicon.ico"
        favicon16x16: "favicon-16x16.png"
        favicon32x32: "favicon-32x32.png"
        apple_touch_icon: "apple-touch-icon.png"
        safari_pinned_tab: "safari-pinned-tab.svg"