backend:
  name: git-gateway
  branch: main

media_folder: "content/uploads"
public_folder: "/uploads"
display_url: https://blog.planter.garden
logo_url: https://planter.garden/favicon.svg
format: toml

collections:
  - name: "posts"
    label: "Blog post"
    folder: "content/posts"
    slug: "{{fields.slug}}"
    path: "{{slug}}/index"
    media_folder: ''
    public_folder: ''
    create: true
    format: "toml-frontmatter"
    fields:
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: true
        required: true
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "URL Path (defaults to title)"
        hint: "The URL Path goes at the end of the URL, for example https://blog.planter.garden/posts/{URL_PATH_HERE}. By default, the post title is used. If the title is really long, consider adding a shorter URL."
        name: "slug"
        widget: "string"
        required: false
        pattern: [ '^[.a-zA-Z0-9-]+$', "Must only contain letters, numbers, and dashes." ]
      - label: "Date"
        name: "date"
        widget: "datetime"
        required: false
      - label: "Author"
        name: "author"
        widget: "string"
        required: true
      - label: "Related Plants"
        name: "plants"
        widget: "list"
        required: false
        summary: "{{fields.plant}}"
        field: { label: "Plant", name: "plant", widget: "string" }
      - label: "Series"
        name: "series"
        widget: "list"
        required: false
        summary: "{{fields.series}}"
        field: { label: "Series", name: "series", widget: "string" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        summary: "{{fields.tag}}"
        field: { label: "Tag", name: "tag", widget: "string" }
      - label: "Weight (default blank, use lower number to pin post)"
        name: "weight"
        widget: "number"
        value_type: "int"
        min: 1
        max: 10
        required: false
      - label: "Cover"
        name: "cover"
        widget: "object"
        required: false
        fields:
          - label: "Cover Photo"
            name: "image"
            widget: "image"
            required: false
            choose_url: false
            media_library:
              config:
                multiple: false
          - label: "Alt Text"
            name: "alt"
            widget: "string"
            required: false
          - label: "Caption"
            name: "caption"
            widget: "string"
            required: false
          - label: "Relative"
            name: "relative"
            widget: "hidden"
            default: false
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "post-legacy"
    label: "Blog post (legacy folder)"
    folder: "content/posts"
    create: true
    format: "toml-frontmatter"
    fields:
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: true
        required: true
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Date"
        name: "date"
        widget: "date"
        required: false
      - label: "Author"
        name: "author"
        widget: "string"
        required: false
      - label: "Related Plants"
        name: "plants"
        widget: "list"
        required: false
      - label: "Series"
        name: "series"
        widget: "list"
        required: false
      - label: "Cover"
        name: "cover"
        widget: "object"
        required: false
        fields:
          - label: "Cover Photo"
            name: "image"
            widget: "image"
            choose_url: false
            media_library:
              config:
                multiple: false
          - label: "Alt Text"
            name: "alt"
            widget: "string"
            required: false
          - label: "Caption"
            name: "caption"
            widget: "string"
            required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "author"
    label: "Author"
    folder: "content/author"
    path: "{{slug}}/_index"
    create: true
    format: "toml-frontmatter"
    fields:
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: true
        required: true
      - label: "Name"
        name: "title"
        widget: "string"
        required: true
      - label: "Cover"
        name: "cover"
        widget: "object"
        required: false
        fields:
          - label: "Cover Photo"
            name: "image"
            widget: "image"
            choose_url: false
            media_library:
              config:
                multiple: false
          - label: "Alt Text"
            name: "alt"
            widget: "string"
            required: false
          - label: "Caption"
            name: "caption"
            widget: "string"
            required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "series"
    label: "Series"
    folder: "content/series"
    path: "{{slug}}/_index"
    create: true
    format: "toml-frontmatter"
    fields:
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: true
        required: true
      - label: "Name"
        name: "title"
        widget: "string"
        required: true
      - label: "Description"
        name: "description"
        hint: "This appears in the series widget."
        widget: "string"
      - label: "Cover"
        name: "cover"
        widget: "object"
        required: false
        fields:
          - label: "Cover Photo"
            name: "image"
            widget: "image"
            choose_url: false
            required: false
            media_library:
              config:
                multiple: false
          - label: "Alt Text"
            name: "alt"
            widget: "string"
            required: false
          - label: "Caption"
            name: "caption"
            widget: "string"
            required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "tags"
    label: "Tags"
    folder: "content/tags"
    path: "{{slug}}/_index"
    create: true
    format: "toml-frontmatter"
    fields:
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: true
        required: true
      - label: "Name"
        name: "title"
        widget: "string"
        required: true
      - label: "Description"
        name: "description"
        widget: "string"
      - label: "Cover"
        name: "cover"
        widget: "object"
        required: false
        fields:
          - label: "Cover Photo"
            name: "image"
            widget: "image"
            choose_url: false
            required: false
            media_library:
              config:
                multiple: false
          - label: "Alt Text"
            name: "alt"
            widget: "string"
            required: false
          - label: "Caption"
            name: "caption"
            widget: "string"
            required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "docs"
    label: "Blog documentation"
    folder: "content/docs"
    slug: "{{fields.slug}}"
    path: "{{slug}}/index"
    media_folder: ''
    public_folder: ''
    create: true
    format: "toml-frontmatter"
    fields:
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: true
        required: true
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "URL Path (defaults to title)"
        name: "slug"
        widget: "string"
        required: false
        pattern: [ '^[.a-zA-Z0-9-]+$', "Must only contain letters, numbers, and dashes." ]
      - label: "Date"
        name: "date"
        widget: "datetime"
        required: false
      - label: "Author"
        name: "author"
        widget: "string"
        required: true
      - label: "Related Plants"
        name: "plants"
        widget: "list"
        required: false
        summary: "{{fields.plant}}"
        field: { label: "Plant", name: "plant", widget: "string" }
      - label: "Series"
        name: "series"
        widget: "list"
        required: false
        summary: "{{fields.series}}"
        field: { label: "Series", name: "series", widget: "string" }
      - label: "Weight (default 5, use lower number to pin post)"
        name: "weight"
        widget: "number"
        default: 5
        value_type: "int"
        min: 1
        max: 10
        required: true
      - label: "Cover"
        name: "cover"
        widget: "object"
        required: false
        fields:
          - label: "Cover Photo"
            name: "image"
            widget: "image"
            required: true
            choose_url: false
            media_library:
              config:
                multiple: false
          - label: "Alt Text"
            name: "alt"
            widget: "string"
            required: true
          - label: "Caption"
            name: "caption"
            widget: "string"
            required: false
          - label: "Relative"
            name: "relative"
            widget: "hidden"
            default: true
      - label: "Body"
        name: "body"
        widget: "markdown"